// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "list.get_all", input: never, result: ({ id: string; name: string; description: string; requires_confirmation: boolean; created_at: string; updated_at: string })[] } | 
        { key: "media.get_all", input: never, result: ({ id: string; filename: string })[] } | 
        { key: "setttings.get_all", input: never, result: Settings[] } | 
        { key: "smtp.get", input: never, result: ({ id: string; smtp_host: string; smtp_port: number; smtp_user: string; auth_protocol: string; tls: string; helo_host: string; smtp_from: string; smtp_tls: boolean; max_connections: number; max_retries: number; idle_timeout: number; wait_timeout: number; custom_headers: string; created_at: string; Subscriber: Subscriber[] })[] } | 
        { key: "user.authenticated", input: never, result: boolean } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "auth.login", input: AuthLoginArgs, result: string } | 
        { key: "list.create", input: ListCreateInput, result: null } | 
        { key: "list.delete", input: ListDeleteInput, result: null } | 
        { key: "media.delete", input: string, result: null } | 
        { key: "media.upload", input: UploadInput, result: Media } | 
        { key: "smtp.create", input: SMTPCreateArgs, result: SmtpSettings } | 
        { key: "smtp.delete", input: string, result: SmtpSettings } | 
        { key: "smtp.edit", input: SmtpSettings, result: SmtpSettings },
    subscriptions: never
};

export type AuthLoginArgs = { username: string; password: string }

export type Media = { id: string; filename: string; content: number[]; created_at: string }

export type ListCreateInput = { name: string; description: string; requires_confirmation: boolean }

export type SmtpSettings = { id: string; smtp_host: string; smtp_port: number; smtp_user: string; smtp_pass: string; auth_protocol: string; tls: string; helo_host: string; smtp_from: string; smtp_tls: boolean; max_connections: number; max_retries: number; idle_timeout: number; wait_timeout: number; custom_headers: string; created_at: string; updated_at: string }

export type SMTPCreateArgs = { smtp_host: string; smtp_port: string; smtp_username: string; smtp_password: string; helo_name: string; from_address: string; tls: string; smtp_tls: boolean; auth_protocol: string; max_connections: number; max_retries: number; idle_timeout: number; wait_timeout: number; custom_headers: string }

export type UploadInput = { content: number[]; filename: string }

export type ListDeleteInput = { id: string }

export type Subscriber = { id: string; email: string; name: string; status: string; created_at: string; updated_at: string; smtpId: string }

export type Settings = { id: string; key: string; value: string; created_at: string }
